### ISSUE TITLE
¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by Gabriel55ita** [AngelFireLA/Brawler-Maker-Modding-tool-for-Brawl-Stars#3]
Why you don't split the code into multiple files?
It will make your life much easier

**Comment by AngelFireLA** [comment]
I'm not very good at python but I already tought of it, but anyway, until it's really a problem/affect performances i think I won't change (and you know, some dumb people wouldn't understand why their main.py have an error when they just have it)

**Comment by Gabriel55ita** [comment]
Understandable
